"use client";

import React from 'react';

export default function ChatWindow() {
  return (
    <div className="p-4 border border-outline/10 rounded-lg bg-surface">
      <h3 className="text-lg font-semibold">ChatWindow Component</h3>
      <p className="text-sm text-on-surface-variant">Stub generated by SentinelAI.</p>
    </div>
  );
}