import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "inverse-primary": "#005db8",
              "primary": "#aac7ff",
              "surface-dim": "#10131b",
              "on-secondary-fixed": "#1a1b1f",
              "primary-fixed-dim": "#aac7ff",
              "error-container": "#93000a",
              "surface-container-low": "#181c23",
              "primary-fixed": "#d6e3ff",
              "on-tertiary-container": "#4a1b00",
              "secondary-fixed-dim": "#c6c6cb",
              "on-tertiary-fixed-variant": "#793100",
              "tertiary-container": "#eb6a12",
              "on-secondary-fixed-variant": "#46464b",
              "error": "#ffb4ab",
              "surface-container-high": "#262a32",
              "on-primary-fixed": "#001b3e",
              "tertiary-fixed": "#ffdbcb",
              "inverse-on-surface": "#2d3038",
              "on-primary": "#003064",
              "tertiary-fixed-dim": "#ffb691",
              "surface-variant": "#31353d",
              "on-primary-container": "#002957",
              "on-secondary": "#2f3034",
              "background": "#10131b",
              "on-surface-variant": "#c0c6d6",
              "surface-bright": "#363941",
              "surface-tint": "#aac7ff",
              "surface-container": "#1c2027",
              "primary-container": "#3e90ff",
              "on-background": "#e0e2ed",
              "outline": "#8b91a0",
              "on-error": "#690005",
              "surface-container-highest": "#31353d",
              "secondary": "#c6c6cb",
              "outline-variant": "#414754",
              "inverse-surface": "#e0e2ed",
              "on-tertiary": "#552000",
              "on-secondary-container": "#b5b4ba",
              "secondary-container": "#46464b",
              "surface": "#10131b",
              "on-error-container": "#ffdad6",
              "on-tertiary-fixed": "#341100",
              "on-primary-fixed-variant": "#00468d",
              "tertiary": "#ffb691",
              "surface-container-lowest": "#0b0e15",
              "on-surface": "#e0e2ed",
              "secondary-fixed": "#e3e2e7",
              "teal-400": "#2dd4bf",
              "teal-500": "#14b8a6",
              "zinc-100": "#f4f4f5",
              "zinc-200": "#e4e4e7",
              "zinc-300": "#d4d4d8",
              "zinc-400": "#a1a1aa",
              "zinc-500": "#71717a",
              "zinc-700": "#3f3f46",
              "zinc-800": "#27272a",
              "zinc-900": "#18181b",
              "zinc-950": "#09090b",
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "margin": "24px",
              "2xl": "48px",
              "gutter": "16px",
              "xl": "32px",
              "md": "16px",
              "sm": "8px",
              "3xl": "64px",
              "lg": "24px",
              "base": "4px",
              "xs": "4px"
          },
          "fontFamily": {
              "label-md": ["Inter"],
              "label-sm": ["Inter"],
              "body-md": ["Inter"],
              "body-lg": ["Inter"],
              "display-lg": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "headline-lg": ["Inter"],
              "headline-md": ["Inter"]
          },
          "fontSize": {
              "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
              "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
          }
      }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
export default config;
